config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "locations#index"

  resources :locations do
    resources :recordings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :recordings, dependent: :destroy
    validates :name, presence: true
end

app/models/recording.rb
class Recording < ApplicationRecord
    belongs_to :location
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    before_action :find_location, only: [:edit, :update, :show, :delete]
    before_action :authenticate_user!, except: [:index, :show]
    def index
        @locations = Location.all
      end
    
      def new
        @location = Location.new
      end
    
      def create
        @location = Location.new(location_params)
        @location.save

        redirect_to @location
      end
    
      def edit
      end
    
      def update
        if @location.update(location_params)
          flash[:notice] = "Successfully updated location!"
          redirect_to @location
        else
          flash[:alert] = "Error updating location!"
          render :edit
        end
      end
    
      def show
      end
    
      def destroy
        @location.destroy
        redirect_to locations_path
      end
    
      private
    
      def location_params
        params.require(:location).permit(:name)
      end
    
      def find_location
        @location = Location.find(params[:id])
      end
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
    before_action :authenticate_user!

    def create
        @location = Location.find(params[:location_id])
        @recording = @location.recordings.build(recording_param)
        if @recording.save 
          redirect_to @location
        else
            render :new
        end    
    end
    def destroy
        @location = Location.find(params[:location_id])
        @recording = @location.recordings.find(params[:id])
        @recording.destroy
        redirect_to @location
      end

    def new
		@location = Location.find(params[:location_id])
		@recording = @location.recordings.build
	end

    private
  def recording_param
     params.require(:recording).permit(:status, :temp) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clima App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/locations/_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%=  simple_form_for @location do |f| %>
     <div class="field">
      <%= f.text_field :name, class: "form-control" %>
     </div>
     
     <%= f.submit "Save", class: "btn btn-success"  %>
    <% end %>
  </div>
</div>

app/views/locations/edit.html.erb
<h2>Edit Location</h2>

<%= render "locations/form" %>

app/views/locations/index.html.erb
<div class="container">
<div class="text-center">
 <h1>LOCATIONS <span class="badge"><%=@locations.count%></span></h1>
 </div>
  <div class="col-sm-10 col-sm-offset-1 col-xs-12 blog-content">
    <% @locations.each do |location| %>
    <div class="col-xs-12">
      <div class="text-center">
        <h2><%= link_to location.name, location %></h2>
        <h6><%= location.created_at.strftime('%b %d, %Y') %></h6>
        <tbody>
                <% location.recordings.each do |rec| %>
                 <tr>
                 <button type="button" class="btn btn-primary"><%= rec.status %><span class="badge"><%=rec.temp%></span></button>
                     <td><%= link_to "Borrar", location_recording_path(rec.location, rec), method: :delete, data: {confirm: "You SUre?"}  %></td>
                </tr>
                <% end %>
        </tbody>
      </div>
      <br>
    </div>
    <% end %>
  </div>
</div>

app/views/locations/new.html.erb
<h2>Create New Location</h2>

<%= render "locations/form" %>

app/views/locations/show.html.erb
<div class="row">
  <div class="col-md-5 col-md-offset-2">
    <h3><%= @location.name %></h3>

    <p>
        Created <%= time_ago_in_words(@location.created_at) %> Ago
        
        <% if user_signed_in? %>
        
          | <button type="button" class="btn btn-success"><%= link_to "Edit", edit_location_path(@location) %> </button>
          | <button type="button" class="btn btn-danger"><%= link_to "Delete", location_path(@location), method: :delete, 
                data: {confirm: 'Are you sure?'} %></button>
          |  <button type="button" class="btn btn-basic"><%= link_to "Add Recording", new_location_recording_path(@location) %></button>
        <% end %>

        <% if @location.recordings.any? %>
            <div>
                <h2>Recording: </h2>
                <table border="2">
                    <thead>
                        <th>Temp</th>
                        <th>Estatus</th>
                <th>
                </th>
                    </thead>
                    <tbody>
                        <%= render @location.recordings%>
                    </tbody>
                </table>
            </div>
        <% else %>
            <p><em>No Recordings.</em></p>
        <% end %>

    </p>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse  navbar-static-top">  
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Weather-App", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "All Locations", root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "New Location", new_location_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%=current_user.name%> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#"><%= link_to "Edit User", edit_user_registration_path%></a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#"><%= link_to "Sign out", destroy_user_session_path, method: :delete%></a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path%></li>
          <li><%= link_to "Sign In", new_user_session_path%></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/recordings/_form.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<%= simple_form_for([@location, @location.recordings.build]) do |f| %>
			<div class="field">
				<%= f.number_field :temp, class: "form-control" %>
			</div>

			<div class="field">
				<%= f.text_field :status, class: "form-control" %>
			</div>

			<%= f.submit "Save Recording", class: "form-control" %>
		<% end %>
	</div>
</div>

app/views/recordings/_recording.html.erb
<tr>
    <td><%= recording.temp %></td>
    <td><%= recording.status %></td>
  <td><%= link_to "DELETE", location_recording_path(recording.location, recording), method: :delete, data: {confirm: "Are You Sure?"}  %></td>
</tr>

app/views/recordings/new.html.erb
<div class="text-center">
	<h1> New Recording </h1>
</div>

<%= render 'form' %>